# config.yaml

# Server configuration
server:
  port: ":8080"          # Server address and port


# Database configuration
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "Vanshika@9"       # Replace with your actual password
  name: "test"      # Name of your database

# JWT configuration
jwt:
  secret: "your_secret_key"   # Secret key for JWT signing; ensure this is secure and unique
  expiration_hours: 72        # Token expiration time in hours

# Logging configuration
logging:
  level: "info"               # Log level (e.g., debug, info, warn, error)

# Security settings
security:
  allowed_users:              # List of users allowed to access the application
    - "john_doe"
    - "jane_smith"
    - "super_admin"
    - "alice_jones"
